get ready for release

diff --git a/automydumper b/automydumper
--- a/automydumper
+++ b/automydumper
@@ -16,8 +16,11 @@ mysql_socket=
 threads=4
 mydumper_opts=''
 enabled=1
-mail_rcpts=''
-mail_from="automydumper@${HOSTNAME}"
+use_savepoints=1
+less_locking=1
+backup_triggers=1
+backup_events=1
+backup_routines=1
 
 version="1.3.0"
 
@@ -45,11 +48,14 @@ export AUTOMYDUMPER_BACKUP_DIR="${backup_dir}"
 export AUTOMYDUMPER_EXIT_CODE=0
 export AUTOMYDUMPER_EXIT_MESSAGE=
 
-mydumper_opts="${mydumper_opts} --less-locking --triggers --events --routines -o ${backup_dir} -v 3 --use-savepoints --threads ${threads}"
+mydumper_opts="${mydumper_opts} -o ${backup_dir} -v 3 --threads ${threads}"
 
-# Compression support
-[ $compress -eq 1 ] && mydumper_opts="$mydumper_opts --compress"
-
+[ ${compress} -eq 1 ] && mydumper_opts="${mydumper_opts} --compress"
+[ ${use_savepoints} -eq 1 ] && mydumper_opts="${mydumper_opts} --use-savepoints"
+[ ${less_locking} -eq 1 ] && mydumper_opts="${mydumper_opts} --less-locking"
+[ ${backup_triggers} -eq 1 ] && mydumper_opts="${mydumper_opts} --triggers"
+[ ${backup_events} -eq 1 ] && mydumper_opts="${mydumper_opts} --events"
+[ ${backup_routines} -eq 1 ] && mydumper_opts="${mydumper_opts} --routines"
 
 options=$(getopt -o h -o f --long help --long force -- "$@")
 [ $? -eq 0 ] || {
@@ -114,7 +120,6 @@ function check_mysql_connection()
 
 function cleanup_backups()
 {
-
     [ ${AUTOMYDUMPER_EXIT_CODE} -gt 0 ] && return
 
     if [ ${keep} -eq 0 ]; then
@@ -128,7 +133,6 @@ function cleanup_backups()
         rm -rf "${oldest}"
     done
     echo ""
-
 }
 
 function handle_error()
@@ -170,7 +174,6 @@ function run_commands()
 
 function overwrite_previous_backup()
 {
-  # &&
     [ ${AUTOMYDUMPER_EXIT_CODE} -gt 0 ] && return
 
     if [ ${overwrite_backup} -eq 0 ]; then
@@ -188,8 +191,7 @@ function overwrite_previous_backup()
 
     # Remove broken latest symlink if backup it's pointing to is no longer there.
     [ ! -e "${backup_root_dir}/latest" ] && rm -f "${backup_root_dir}/latest"
-
-  }
+}
 
 function symlink_latest()
 {
@@ -207,7 +209,6 @@ function run_mydumper()
     else
         handle_error "Mydumper could not complete backup"
     fi
-
 }
 
 function show_header()
@@ -243,6 +244,8 @@ if [ $enabled -eq 0 ]; then
     echo "Automydumper is disabled. Enable by removing enabled=0. Quitting."
     exit 0
 fi
+
+trap "{ echo '!! Script interrupted.'; handle_error 'Backup interrupted'; }" INT
 
 validate_date_format
 
